'''Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed
correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a
“bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the
correct number, the game is over. Keep track of the number of guesses the user makes throughout the game and tell the
user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
#  >>> 1234
  2 cows, 0 bulls
#  >>> 1256
  1 cow, 1 bull
  ...'''

from random import randint

def cow_bull():
    correct, guesses, rand_num = False, 0, list(str(randint(1000, 9999)))

    while correct == False:
        cows, bulls = 0, 0
        print ('Number is: {}'.format(rand_num)) # For testing only
        guess = list(str(input('Guess a 4 digit number: ')))
        guesses += 1
        if guess == rand_num:
            break # Break out of the loop and return the guesses
        else:
            for x, y in zip(guess, rand_num):
                if x == y:
                    cows += 1
                elif x in rand_num:
                    bulls += 1
            print('{} cows, {} bulls'.format(cows, bulls))
    return print('You guessed correctly and it took you {} guesses.'.format(guesses))




if __name__=="__main__":
    cow_bull()